defaults:
  - scope:
      path: ''
    values:
      layout: 'page'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
  - scope:
      path: ''
      type: 'members'
    values:
      layout: 'member'

permalink: /nieuws/:year/:month/:day/:title/

collections:
  members:
    output: true
    permalink: /team/:path/
  treatments:
    output: true
    permalink: /treatments/:path/
  collecties:
    output: true
    permalink: /collections/:path/

title: 'Koffijberg Hairdressers in Amsterdam'
url: https://www.koffijberghairdressers.com
twitter_url: https://twitter.com/KoffijbergHair